### PR TITLE
CLI Refactor Design CEP

### PR DESCRIPTION
**Pull request by thedrow**
This is the Design CEP for celery/celery#5718.
Besides some missing links and a few touches it is done.

Who is going to shepherd this CEP?

### CODE REVIEW

**Comment by thedrow** [comment]
How do we feel about using https://github.com/tiangolo/typer?
It does look like it can simplify our code further and it is based on click.

**Comment by auvipy** [comment]
wow! we are thinking the same! check https://github.com/celery/celery/pull/5718#issuecomment-569178788

**Comment by thedrow** [comment]
Typer currently doesn't support async CLI commands. I've discussed with the maintainer how it might be done.

Since celery/celery#5718 was merged this should be accepted.
I'll move it to the accepted folder and fix the remaining problems in CI.

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
https://github.com/tiangolo/typer/pull/213

**Pull request merged**
